---
- name: Ensure renew-cert.timer is present
  ansible.builtin.template:
    src: ./templates/systemd/renew-cert.timer.j2
    dest: /etc/systemd/system/renew-cert.timer
    owner: root
    group: root
    mode: 0644

- name: Ensure renew-cert.service is present
  ansible.builtin.template:
    src: ./templates/systemd/renew-cert.service.j2
    dest: /etc/systemd/system/renew-cert.service
    owner: root
    group: root
    mode: 0644

- name: Ensure renew-cert.timer is enabled
  ansible.builtin.systemd:
    name: renew-cert.timer
    enabled: yes
    state: started
    daemon_reload: yes
