---
- import_tasks: include-vars.yml

- ansible.builtin.import_tasks: install-with-snapd.yml

- ansible.builtin.import_tasks: register-account.yml
  when: certbot_register_account

- ansible.builtin.include_tasks: order-certificate-dns.yml
  loop: "{{ certbot_certifactes }}"
  when:
    - certbot_create_if_missing
    - cert_item.mode == 'dns'
  loop_control:
    loop_var: cert_item