---
#########################################
#            _             _ _          #
#           | |           (_) |         #
#           | | __ ___   ___| | __      #
#       _   | |/ _` \ \ / / | |/ /      #
#      | |__| | (_| |\ V /| |   <       #
#       \____/ \__,_| \_/ |_|_|\_\      #
#                                       #
#########################################

- import_tasks: include-vars.yml

- ansible.builtin.import_tasks: install-with-snapd.yml

- name: Include DNS certificate order tasks
  ansible.builtin.include_tasks: order-certificate-dns.yml
  loop: "{{ certbot_certificates }}"
  when:
    - certbot_create_if_missing
    - cert_item.mode == 'dns'
    - certbot_certificates is defined
  loop_control:
    loop_var: cert_item

- name: Include standalone certificate order tasks
  ansible.builtin.include_tasks: order-certificate-standalone.yml
  loop: "{{ certbot_certificates }}"
  when:
    - certbot_create_if_missing
    - cert_item.mode == 'standalone'
    - certbot_certificates is defined
  loop_control:
    loop_var: cert_item

- name: Include systemd timer creation tasks
  ansible.builtin.include_tasks: create-timer.yml
  when: ansible_service_mgr == 'systemd'
