---
  - name: Install snapd
    ansible.builtin.apt:
      name: snapd
      state: present
      update_cache: true

  - name: Install certbot
    community.general.snap:
      name: certbot
      classic: true
      state: present

  - name: Trust plugins with root
    ansible.builtin.command:
      cmd: "snap set certbot trust-plugin-with-root=ok && echo 'ok' > /tmp/certbot_trust_plugin_with_root"
      creates: /tmp/certbot_trust_plugin_with_root
    when: certbot_dns_plugins | length > 0
  
  - name: Install certbot-dns-plugins
    community.general.snap:
      name: certbot-dns-{{ item }}
      state: present
    loop: "{{ certbot_dns_plugins }}"
    when: certbot_dns_plugins | length > 0

