---
  - name: Install snapd
    ansible.builtin.apt:
      name: snapd
      state: present
      update_cache: true

  - name: Install certbot
    community.general.snap:
      name: certbot
      classic: true
      state: present

  - name: Trust plugins with root
    ansible.builtin.command: snap set certbot trust-plugin-with-root=ok
    when: cerbot_dns_plugins | length > 0
  
  - name: Install certbot-dns-{{ item }} plugin
    community.general.snap:
      name: certbot-dns-{{ item }}
      dangerous: true
      classic: true
      state: present
    loop: "{{ cerbot_dns_plugins }}"
    when: cerbot_dns_plugins | length > 0

