---
  - name: Install snapd
    ansible.builtin.apt:
      name: snapd
      state: present
      update_cache: true

  - name: Install certbot
    community.general.snap:
      name: certbot
      classic: true
      state: present
  
  - name: Install certbot-dns-cloudflare
    community.general.snap:
      name: certbot-dns-cloudflare
      dangerous: true
      classic: true
      state: present
